// Auto-generated by optimize-images.js
// Run 'npm run optimize-images' to regenerate

import Capri_2022 from './optimized/capri--2022-medium.webp'
import Corsica_2025 from './optimized/corsica-2025-medium.webp'
import Croazia_2024 from './optimized/croazia-2024-medium.webp'
import Croce_Bianca_2021 from './optimized/croce-bianca-2021-medium.webp'
import Laurea_Francesca_2024 from './optimized/laurea-francesca-2024-medium.webp'
import Macugnaga_2024 from './optimized/macugnaga-2024-medium.webp'
import Marocco_2024 from './optimized/marocco--2024-medium.webp'
import New_York_2025 from './optimized/new-york--2025-medium.webp'
import Parcheggi from './optimized/parcheggi-medium.webp'
import ParcheggioGrande from './optimized/parcheggiogrande-medium.webp'
import Puglia_2023 from './optimized/puglia-2023-medium.webp'
import Riva_Trigoso_2023 from './optimized/riva-trigoso-2023-medium.webp'
import Saint_Tropez_2025 from './optimized/saint-tropez-2025-medium.webp'
import Sardegna_2025 from './optimized/sardegna-2025-medium.webp'
import Tanzania_2024 from './optimized/tanzania-2024-medium.webp'
import Zanzibar_2025 from './optimized/zanzibar---2025-medium.webp'
import castello from './optimized/castello-medium.webp'
import chiesa from './optimized/chiesa-medium.webp'
import parcheggioPiccolo from './optimized/parcheggiopiccolo-medium.webp'

export const imagesMap = {
  "Capri-2022": { medium: Capri_2022, thumb: Capri_2022, small: Capri_2022, large: Capri_2022, full: Capri_2022 },
  "Corsica-2025": { medium: Corsica_2025, thumb: Corsica_2025, small: Corsica_2025, large: Corsica_2025, full: Corsica_2025 },
  "Croazia-2024": { medium: Croazia_2024, thumb: Croazia_2024, small: Croazia_2024, large: Croazia_2024, full: Croazia_2024 },
  "Croce-Bianca-2021": { medium: Croce_Bianca_2021, thumb: Croce_Bianca_2021, small: Croce_Bianca_2021, large: Croce_Bianca_2021, full: Croce_Bianca_2021 },
  "Laurea-Francesca-2024": { medium: Laurea_Francesca_2024, thumb: Laurea_Francesca_2024, small: Laurea_Francesca_2024, large: Laurea_Francesca_2024, full: Laurea_Francesca_2024 },
  "Macugnaga-2024": { medium: Macugnaga_2024, thumb: Macugnaga_2024, small: Macugnaga_2024, large: Macugnaga_2024, full: Macugnaga_2024 },
  "Marocco-2024": { medium: Marocco_2024, thumb: Marocco_2024, small: Marocco_2024, large: Marocco_2024, full: Marocco_2024 },
  "New-York-2025": { medium: New_York_2025, thumb: New_York_2025, small: New_York_2025, large: New_York_2025, full: New_York_2025 },
  "Parcheggi": { medium: Parcheggi, thumb: Parcheggi, small: Parcheggi, large: Parcheggi, full: Parcheggi },
  "ParcheggioGrande": { medium: ParcheggioGrande, thumb: ParcheggioGrande, small: ParcheggioGrande, large: ParcheggioGrande, full: ParcheggioGrande },
  "Puglia-2023": { medium: Puglia_2023, thumb: Puglia_2023, small: Puglia_2023, large: Puglia_2023, full: Puglia_2023 },
  "Riva-Trigoso-2023": { medium: Riva_Trigoso_2023, thumb: Riva_Trigoso_2023, small: Riva_Trigoso_2023, large: Riva_Trigoso_2023, full: Riva_Trigoso_2023 },
  "Saint-Tropez-2025": { medium: Saint_Tropez_2025, thumb: Saint_Tropez_2025, small: Saint_Tropez_2025, large: Saint_Tropez_2025, full: Saint_Tropez_2025 },
  "Sardegna-2025": { medium: Sardegna_2025, thumb: Sardegna_2025, small: Sardegna_2025, large: Sardegna_2025, full: Sardegna_2025 },
  "Tanzania-2024": { medium: Tanzania_2024, thumb: Tanzania_2024, small: Tanzania_2024, large: Tanzania_2024, full: Tanzania_2024 },
  "Zanzibar-2025": { medium: Zanzibar_2025, thumb: Zanzibar_2025, small: Zanzibar_2025, large: Zanzibar_2025, full: Zanzibar_2025 },
  "castello": { medium: castello, thumb: castello, small: castello, large: castello, full: castello },
  "chiesa": { medium: chiesa, thumb: chiesa, small: chiesa, large: chiesa, full: chiesa },
  "parcheggioPiccolo": { medium: parcheggioPiccolo, thumb: parcheggioPiccolo, small: parcheggioPiccolo, large: parcheggioPiccolo, full: parcheggioPiccolo }
}

export function getSrcSet(imageObj) {
  return `${imageObj.medium} 800w`
}

export function getSizes(defaultSize = '100vw') {
  return `(max-width: 768px) 100vw, ${defaultSize}`
}
