// Auto-generated by optimize-images.js
// Run 'npm run optimize-images' to regenerate

import barca_thumb from './optimized/barca-thumb.webp'
import barca_small from './optimized/barca-small.webp'
import barca_medium from './optimized/barca-medium.webp'
import barca_large from './optimized/barca-large.webp'
import barca_full from './optimized/barca-full.webp'
import couple1_thumb from './optimized/couple1-thumb.webp'
import couple1_small from './optimized/couple1-small.webp'
import couple1_medium from './optimized/couple1-medium.webp'
import couple1_large from './optimized/couple1-large.webp'
import couple1_full from './optimized/couple1-full.webp'
import home_pic_thumb from './optimized/home_pic-thumb.webp'
import home_pic_small from './optimized/home_pic-small.webp'
import home_pic_medium from './optimized/home_pic-medium.webp'
import home_pic_large from './optimized/home_pic-large.webp'
import home_pic_full from './optimized/home_pic-full.webp'
import mare_thumb from './optimized/mare-thumb.webp'
import mare_small from './optimized/mare-small.webp'
import mare_medium from './optimized/mare-medium.webp'
import mare_large from './optimized/mare-large.webp'
import mare_full from './optimized/mare-full.webp'
import paddle_thumb from './optimized/paddle-thumb.webp'
import paddle_small from './optimized/paddle-small.webp'
import paddle_medium from './optimized/paddle-medium.webp'
import paddle_large from './optimized/paddle-large.webp'
import paddle_full from './optimized/paddle-full.webp'
import sci_thumb from './optimized/sci-thumb.webp'
import sci_small from './optimized/sci-small.webp'
import sci_medium from './optimized/sci-medium.webp'
import sci_large from './optimized/sci-large.webp'
import sci_full from './optimized/sci-full.webp'
import splash_thumb from './optimized/splash-thumb.webp'
import splash_small from './optimized/splash-small.webp'
import splash_medium from './optimized/splash-medium.webp'
import splash_large from './optimized/splash-large.webp'
import splash_full from './optimized/splash-full.webp'
import vela_thumb from './optimized/vela-thumb.webp'
import vela_small from './optimized/vela-small.webp'
import vela_medium from './optimized/vela-medium.webp'
import vela_large from './optimized/vela-large.webp'
import vela_full from './optimized/vela-full.webp'
import whitecross_thumb from './optimized/whitecross-thumb.webp'
import whitecross_small from './optimized/whitecross-small.webp'
import whitecross_medium from './optimized/whitecross-medium.webp'
import whitecross_large from './optimized/whitecross-large.webp'
import whitecross_full from './optimized/whitecross-full.webp'
import zanzi_thumb from './optimized/zanzi-thumb.webp'
import zanzi_small from './optimized/zanzi-small.webp'
import zanzi_medium from './optimized/zanzi-medium.webp'
import zanzi_large from './optimized/zanzi-large.webp'
import zanzi_full from './optimized/zanzi-full.webp'

export const barca = {
  thumb: barca_thumb,
  small: barca_small,
  medium: barca_medium,
  large: barca_large,
  full: barca_full
}

export const couple1 = {
  thumb: couple1_thumb,
  small: couple1_small,
  medium: couple1_medium,
  large: couple1_large,
  full: couple1_full
}

export const home_pic = {
  thumb: home_pic_thumb,
  small: home_pic_small,
  medium: home_pic_medium,
  large: home_pic_large,
  full: home_pic_full
}

export const mare = {
  thumb: mare_thumb,
  small: mare_small,
  medium: mare_medium,
  large: mare_large,
  full: mare_full
}

export const paddle = {
  thumb: paddle_thumb,
  small: paddle_small,
  medium: paddle_medium,
  large: paddle_large,
  full: paddle_full
}

export const sci = {
  thumb: sci_thumb,
  small: sci_small,
  medium: sci_medium,
  large: sci_large,
  full: sci_full
}

export const splash = {
  thumb: splash_thumb,
  small: splash_small,
  medium: splash_medium,
  large: splash_large,
  full: splash_full
}

export const vela = {
  thumb: vela_thumb,
  small: vela_small,
  medium: vela_medium,
  large: vela_large,
  full: vela_full
}

export const whitecross = {
  thumb: whitecross_thumb,
  small: whitecross_small,
  medium: whitecross_medium,
  large: whitecross_large,
  full: whitecross_full
}

export const zanzi = {
  thumb: zanzi_thumb,
  small: zanzi_small,
  medium: zanzi_medium,
  large: zanzi_large,
  full: zanzi_full
}

// Helper to get srcset for responsive images
export function getSrcSet(imageObj) {
  return `${imageObj.small} 400w, ${imageObj.medium} 800w, ${imageObj.large} 1200w`
}

// Helper to get sizes attribute
export function getSizes(defaultSize = '100vw') {
  return `(max-width: 480px) 100vw, (max-width: 768px) 50vw, ${defaultSize}`
}
